package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// applyJitter walks the directory and replaces time.Sleep(X) with _jsleep(X),
// which adds random 0-25% jitter to each sleep duration. This defeats network
// IDS beacon detection (RITA, Zeek) that fingerprints regular intervals.
//
// Tickers (time.NewTicker) are NOT transformed — jittering ticks requires
// replacing the .C channel pattern which is too invasive for AST transform.
// The user should manually jitter ticker intervals if needed.
func applyJitter(dir string) {
	packagesNeedingJitter := make(map[string]string) // dir → package name
	totalSleeps := 0

	filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}
		if strings.Contains(path, "cmd/probe-server") {
			return nil
		}
		if strings.Contains(path, "tools/obfuscate") {
			return nil
		}
		if strings.HasSuffix(path, "zjitter.go") {
			return nil
		}
		if strings.HasSuffix(path, "zdecode.go") {
			return nil
		}
		if strings.Contains(path, "vendor/") {
			return nil
		}

		src, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  ERR reading %s: %v\n", path, err)
			return nil
		}

		result, pkgName, count := jitterFile(path, src)
		if count > 0 {
			pkgDir := filepath.Dir(path)
			packagesNeedingJitter[pkgDir] = pkgName
			os.WriteFile(path, []byte(result), 0644)
			fmt.Printf("  JITTER: %s (%d time.Sleep → _jsleep)\n", path, count)
			totalSleeps += count
		}
		return nil
	})

	// Generate zjitter.go helper for each package that needs it
	for pkgDir, pkgName := range packagesNeedingJitter {
		helperFile := filepath.Join(pkgDir, "zjitter.go")
		content := fmt.Sprintf(`// Code generated by obfuscation tool. DO NOT EDIT.
package %s

import (
	"math/rand"
	"time"
)

func _jsleep(d time.Duration) {
	time.Sleep(d + time.Duration(rand.Int63n(int64(d)/4+1)))
}
`, pkgName)
		os.WriteFile(helperFile, []byte(content), 0644)
		fmt.Printf("  JITTER GEN: %s\n", helperFile)
	}

	fmt.Printf("\n=== Jitter Summary ===\n")
	fmt.Printf("Sleep calls jittered: %d\n", totalSleeps)
	fmt.Printf("Helper files generated: %d packages\n", len(packagesNeedingJitter))
}

// jitterFile finds time.Sleep calls in the AST and replaces the function name
// with _jsleep. Returns (modifiedContent, packageName, sleepCount).
func jitterFile(path string, src []byte) (string, string, int) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  WARN: parse error in %s: %v\n", path, err)
		return string(src), "", 0
	}

	pkgName := ""
	if f.Name != nil {
		pkgName = f.Name.Name
	}

	var repls []Replace
	sleepCount := 0

	ast.Inspect(f, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		// Check if it's time.Sleep(...)
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		ident, ok := sel.X.(*ast.Ident)
		if !ok {
			return true
		}
		if ident.Name != "time" || sel.Sel.Name != "Sleep" {
			return true
		}

		// Found time.Sleep(X) — replace "time.Sleep" with "_jsleep"
		// The arguments stay in place.
		selPos := fset.Position(sel.Pos())
		selEnd := fset.Position(sel.End())
		repls = append(repls, Replace{
			Start: selPos.Offset,
			End:   selEnd.Offset,
			Text:  "_jsleep",
		})
		sleepCount++
		return true
	})

	if sleepCount == 0 {
		return string(src), pkgName, 0
	}

	// Sort by start offset descending (apply from end to beginning)
	sort.Slice(repls, func(i, j int) bool {
		return repls[i].Start > repls[j].Start
	})

	result := string(src)
	for _, r := range repls {
		if r.Start < 0 || r.End > len(result) || r.Start > r.End {
			fmt.Fprintf(os.Stderr, "  WARN: bad offset in %s: %d-%d (len=%d)\n", path, r.Start, r.End, len(result))
			continue
		}
		result = result[:r.Start] + r.Text + result[r.End:]
	}

	return result, pkgName, sleepCount
}